### ISSUE TITLE
Malware analyst 

### ISSUE THREAD

**Issue by edenroz** [thesp0nge/ama#1]
Ciao,

Sono laureato alla magistrale in Ing. Informatica e come tesi di laurea ho effettuato il reverse engineering di XAgent dell APT28.

Da quasi due anni cerco lavoro come malware analyst ma in Italia trovo solo roba da developer. Quelle poche volte che un azienda di sicurezza informatica mi contatta si parla sempre dei blue team, IDS e SIEM... 

Devo arrendermi ad andare all'estero?

**Comment by thesp0nge** [comment]
No no ci sono posizioni anche da noi, poche ma ci sono come ad esempio questa: https://jobs.malwarebytes.com/job/1823788.
Ci sono aziende estere che cercano anche da remoto.

Attento solo a non cadere nelle grandi società di consulenza, perché sono un tritacarne di sogni ed aspirazioni.

Valuta un'esperienza all'estero, male non fa.
